#define PRIOR_IS_UNKNOWN 0
#define PRIOR_IS_GAUSSIAN 1
#define PRIOR_IS_MULTIVARIATE 2
#define PRIOR_IS_GENERALISED 4
#define PRIOR_IS_KERNEL_DENSITY_ESTIMATE 8
#define PRIOR_IS_DVINE_COPULA 16
#define PRIOR_SIGMA_GIVEN 32
#define PRIOR_PRECISION_GIVEN 64
#define PTYPE(OPT,PROPERTY) (((OPT) & (PROPERTY)) > 0)
#define ALSO(OPT,PROPERTY) ((OPT) = ((OPT) | (PROPERTY)))
