%
% ODEmodel11S26P4U_vf.m
%
% MATLAB vector field function for: ODEmodel11S26P4U
%
% This file was generated by the program VFGEN (Version:2.4.1)
% Generated on 16-Dec-2013 at 17:39
%
%
function vf_ = ODEmodel11S26P4U_vf(t,x_,p_)
    X1         = x_(1);
    X2         = x_(2);
    X3         = x_(3);
    X4         = x_(4);
    X5         = x_(5);
    X6         = x_(6);
    X7         = x_(7);
    X8         = x_(8);
    X9         = x_(9);
    X10        = x_(10);
    X11        = x_(11);
    theta_1    = p_(1);
    theta_2    = p_(2);
    theta_3    = p_(3);
    theta_4    = p_(4);
    theta_5    = p_(5);
    theta_6    = p_(6);
    theta_7    = p_(7);
    theta_8    = p_(8);
    theta_9    = p_(9);
    theta_10   = p_(10);
    theta_11   = p_(11);
    theta_12   = p_(12);
    theta_13   = p_(13);
    theta_14   = p_(14);
    theta_15   = p_(15);
    theta_16   = p_(16);
    theta_17   = p_(17);
    theta_18   = p_(18);
    theta_19   = p_(19);
    theta_20   = p_(20);
    theta_21   = p_(21);
    theta_22   = p_(22);
    theta_23   = p_(23);
    theta_24   = p_(24);
    theta_25   = p_(25);
    theta_26   = p_(26);
    u1         = p_(27);
    u2         = p_(28);
    u3         = p_(29);
    u4         = p_(30);
    logistic = (1+exp(-t))^(-1);
    U1t = logistic*u1;
    U2t = u2*logistic;
    U3t = u3*logistic;
    U4t = u4*logistic;
    S1 = X4+X5;
    S2 = X7*theta_22*X9;
    A1 = X2*theta_1;
    A2 = X1*theta_2;
    A3 = theta_3*X2*X3;
    A4 = X4*theta_4;
    A5 = X4*theta_10;
    A51 = theta_10*X5;
    A6 = X7*theta_13;
    A7 = S1*theta_14*X6;
    A8 = X10*S1*theta_19;
    A9 = X8*theta_20;
    A10 = X7*theta_22*X11;
    A11 = X9*theta_21;
    vf_ = zeros(11,1);
    vf_(1) = (0.1+S2)*theta_5-A2-X1*theta_7+A1;
    vf_(2) = A2-X2*theta_8-A1;
    vf_(3) = theta_12*U2t+theta_6-A3-theta_9*X3+A4;
    vf_(4) = -A5+A3-A4;
    vf_(5) = -A51+theta_11*U1t;
    vf_(6) = -theta_16*X6+U3t*theta_18+A6-A7+theta_15;
    vf_(7) = -A6-X7*theta_17+A7;
    vf_(8) = A8-A9-X8*theta_24;
    vf_(9) = -A11+A9;
    vf_(10) = -A8+A10;
    vf_(11) = A11-theta_25*X11+theta_23+theta_26*U4t-A10;

