/*
 *  pendulum_cvs.h
 *
 *  CVODES C prototype file for the functions defined in pendulum_cvs.c
 *
 *  This file was generated by the program VFGEN (Version:2.4.1)
 *  Generated on  6-Feb-2017 at 16:40
 */

int pendulum_vf(realtype, N_Vector, N_Vector, void *);
int pendulum_jac(int, realtype,
                N_Vector, N_Vector,
                DlsMat, void *,
                N_Vector, N_Vector, N_Vector);
int pendulum_jacp(int, realtype,
                N_Vector, N_Vector,
                DlsMat, void *,
                N_Vector, N_Vector, N_Vector);
int pendulum_sens(int, realtype, N_Vector, N_Vector,
                int, N_Vector, N_Vector,
                void *, N_Vector, N_Vector);
int pendulum_func(realtype, N_Vector, realtype *, void *);
int pendulum_func_sens(realtype, N_Vector, N_Vector *, double *, void *);
